version: '3.7'
services:
  node-chromium-db:
    # image:tag
    image: armno/node-chromium:10.15.0-alpine
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    ports:
      # exposed port:container port
      - 3001:3001
    command: sh -c "make deps && npm start"
    depends_on:
      - postgres

  node-chromium:
    image: armno/node-chromium:10.15.0-alpine
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}